name: AITraining

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: x64
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Tests with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html